// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UI.Models;

public partial class DatosGeneralesUsuario
{
    public int Id { get; set; }

    public string UserId { get; set; }

    public string Email { get; set; }

    public string Nombres { get; set; }

    public string Apellidos { get; set; }

    public string Telefono { get; set; }

    public string Cedula { get; set; }

    public int RoleId { get; set; }

    public DateTime CreadoEn { get; set; }

    public DateTime? ActualizadoEn { get; set; }
}