// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UI.Models;

public partial class ProductoImagen
{
    public int Id { get; set; }

    public int ProductoId { get; set; }

    public string NombreArchivo { get; set; }

    public string ContentType { get; set; }

    public long Tamano { get; set; }

    public int Ancho { get; set; }

    public int Alto { get; set; }

    public byte[] Contenido { get; set; }

    public DateTime CreadoEn { get; set; }

    public virtual Productos Producto { get; set; }
}