// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UI.Models;

public partial class Productos
{
    public int Id { get; set; }

    public string Nombre { get; set; }

    public string Codigo { get; set; }

    public int Stock { get; set; }

    public decimal Precio { get; set; }

    public int EstadoId { get; set; }

    public string Imagen { get; set; }

    public virtual Estados Estado { get; set; }

    public virtual ICollection<ProductoImagen> ProductoImagen { get; set; } = new List<ProductoImagen>();
}