// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UI.Models;

public partial class ProductoView
{
    public int id { get; set; }

    public string nombre { get; set; }

    public string codigo { get; set; }

    public int stock { get; set; }

    public decimal precio { get; set; }

    public int estadoId { get; set; }

    public string estadoNombre { get; set; }
}