// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace UI.Models;

public partial class TiendaProductosContext : DbContext
{
    public TiendaProductosContext(DbContextOptions<TiendaProductosContext> options)
        : base(options)
    {
    }

    public virtual DbSet<DatosGeneralesUsuario> DatosGeneralesUsuarios { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<DatosGeneralesUsuario>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__DatosGen__3214EC07A2052CA0");

            entity.ToTable("DatosGeneralesUsuarios", "Usuarios");

            entity.Property(e => e.ActualizadoEn).HasColumnType("datetime");
            entity.Property(e => e.Apellidos)
                .IsRequired()
                .HasMaxLength(150);
            entity.Property(e => e.Cedula)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.CreadoEn)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(256);
            entity.Property(e => e.Nombres)
                .IsRequired()
                .HasMaxLength(150);
            entity.Property(e => e.Telefono)
                .IsRequired()
                .HasMaxLength(25);
            entity.Property(e => e.UserId)
                .IsRequired()
                .HasMaxLength(450);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}